spring.application.name=stock

# =========================
# DataSource
# =========================
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/stock?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Taipei
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# =========================
# JDBC / SQL Init
# =========================
spring.sql.init.mode=never

# =========================
# Jackson
# =========================
spring.jackson.time-zone=Asia/Taipei
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# =========================
# Thymeleaf
# =========================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# =========================
# Server
# =========================
server.port=8080
server.servlet.context-path=/

# =========================
# Logging
# =========================
logging.level.root=INFO
logging.level.tool.stock=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG

# =========================
# Custom App Config
# =========================
app.stock.base-path=C:/Users/user/Desktop/personal/stock
app.stock.market-types=TW_STOCK,ETF
app.stock.backtest.period-days=365
app.stock.prediction.hold-days=5
app.stock.top.limit=10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

